version: '3.7'
services:
  rbp-booking:
    image: mwinteringham/restfulbookerplatform_booking:1.3.0715f79
    ports:
      - "3000:3000"
    restart: always
  rbp-room:
    image: mwinteringham/restfulbookerplatform_room:1.3.0715f79
    ports:
      - "3001:3001"
    restart: always
  rbp-branding:
    image: mwinteringham/restfulbookerplatform_branding:1.3.0715f79
    ports:
      - "3002:3002"
    restart: always
  rbp-assets:
    image: mwinteringham/restfulbookerplatform_assets:1.3.0715f79
    ports:
      - "3003:3003"
    restart: always
  rbp-auth:
    image: mwinteringham/restfulbookerplatform_auth:1.3.0715f79
    ports:
      - "3004:3004"
    restart: always
  rbp-report:
    image: mwinteringham/restfulbookerplatform_report:1.3.0715f79
    ports:
      - "3005:3005"
    restart: always
  rbp-message:
    image: mwinteringham/restfulbookerplatform_message:1.3.0715f79
    ports:
      - "3006:3006"
    restart: always
  rbp-proxy:
    image: mwinteringham/restfulbookerplatform_proxy:latest
    ports:
      - "80:80"
    restart: always
